apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379  # Redis 服务端口
      targetPort: 6379
      nodePort: 30001  # 配置 NodePort，可根据需要修改
